apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: voting-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AryanAtel1034/DevSecOps-GitOps-End-to-End-Infra.git
        revision: HEAD
        directories:
          - path: GitOps/env/dev/*                      # third folder in repo
  template:
    metadata:
      name: '{{path.basename}}'                         # Application name = folder name
    spec:
      project: voting-project                       # Reference the AppProject we created
      source:
        repoURL: https://github.com/AryanAtel1034/DevSecOps-GitOps-End-to-End-Infra.git
        targetRevision: main
        path: '{{path}}'                                 # Path of each folder
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}                                    # Auto-sync enabled
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
